// <auto-generated />
using System;
using ManufacturingERP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManufacturingERP.Migrations
{
    [DbContext(typeof(ManufacturingContext))]
    partial class ManufacturingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManufacturingERP.Models.ActivityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LogId");

                    b.ToTable("ActivityLogs", (string)null);
                });

            modelBuilder.Entity("ManufacturingERP.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<TimeSpan?>("CheckIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("CheckOut")
                        .HasColumnType("time");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Attendances", (string)null);
                });

            modelBuilder.Entity("ManufacturingERP.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LogId")
                        .HasName("PK__AuditLog__5E5499A8B49707C8");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Bom", b =>
                {
                    b.Property<int>("Bomid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BOMID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bomid"));

                    b.Property<int?>("ChildId")
                        .HasColumnType("int")
                        .HasColumnName("ChildID");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Bomid")
                        .HasName("PK__BOM__CA12FCBBE9DDA23D");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentId");

                    b.ToTable("BOM", (string)null);
                });

            modelBuilder.Entity("ManufacturingERP.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<decimal?>("BasicSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ManufacturingERP.Models.EmployeeSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("ShiftID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<DateOnly?>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Employee__9C8A5B69D0265039");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeSchedules");
                });

            modelBuilder.Entity("ManufacturingERP.Models.FinancialTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderRef")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TransactionId");

                    b.ToTable("FinancialTransactions");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Inventory", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.Property<decimal?>("CurrentStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("WarehouseLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaterialId", "WarehouseId")
                        .HasName("PK_Inventory");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("ManufacturingERP.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("PartnerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MinStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang sử dụng");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaterialId")
                        .HasName("PK__Material__C5061317F41CDBDA");

                    b.HasIndex(new[] { "MaterialCode" }, "UQ__Material__170C54BA03BF32BF")
                        .IsUnique();

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Notification", b =>
                {
                    b.Property<int>("NotiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotiId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("RecipientId")
                        .HasColumnType("int")
                        .HasColumnName("RecipientID");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NotiId")
                        .HasName("PK__Notifica__EDC08EF256E350DB");

                    b.HasIndex("RecipientId");

                    b.HasIndex("RoleId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartnerId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PartnerType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Hoạt động");

                    b.Property<string>("TaxCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartnerId");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("ManufacturingERP.Models.PasswordResetRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int?>("ProcessedByAdminId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequestId");

                    b.HasIndex("ProcessedByAdminId");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetRequests");
                });

            modelBuilder.Entity("ManufacturingERP.Models.QualityControl", b =>
                {
                    b.Property<int>("Qcid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QCID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Qcid"));

                    b.Property<string>("DefectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FailedQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("InspectionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("InspectorId")
                        .HasColumnType("int")
                        .HasColumnName("InspectorID");

                    b.Property<int?>("PassedQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("StepNumber")
                        .HasColumnType("int");

                    b.Property<int?>("Woid")
                        .HasColumnType("int")
                        .HasColumnName("WOID");

                    b.Property<int?>("WorkOrderItemId")
                        .HasColumnType("int");

                    b.HasKey("Qcid")
                        .HasName("PK__QualityC__DC29BF92A67EA94A");

                    b.HasIndex("InspectorId");

                    b.HasIndex("Woid");

                    b.HasIndex("WorkOrderItemId");

                    b.ToTable("QualityControl", (string)null);
                });

            modelBuilder.Entity("ManufacturingERP.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A9C5AD3A2");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160E562BA39")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ManufacturingERP.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("ModuleKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.Property<bool>("CanAdd")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.HasKey("RoleId", "ModuleKey");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("ManufacturingERP.Models.Routing", b =>
                {
                    b.Property<int>("RoutingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoutingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoutingId"));

                    b.Property<int?>("EstimatedTime")
                        .HasColumnType("int");

                    b.Property<string>("OutputDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<string>("StepName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("WorkCenter")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoutingId")
                        .HasName("PK__Routings__A763F8A80BA1B9F0");

                    b.HasIndex("ProductId");

                    b.ToTable("Routings");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShiftID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ShiftName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId")
                        .HasName("PK__Shifts__C0A838E1B1902443");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ManufacturingERP.Models.StockTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int")
                        .HasColumnName("PartnerID");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TransBy")
                        .HasColumnType("int")
                        .HasColumnName("TransBy");

                    b.Property<DateTime?>("TransDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.HasKey("TransactionId")
                        .HasName("PK__StockTra__55433A4B1AE83A43");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("TransBy");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockTransactions", (string)null);
                });

            modelBuilder.Entity("ManufacturingERP.Models.SystemSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingId");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("ManufacturingERP.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACD5200C46");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E418C8924B")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<decimal?>("Capacity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CapacityUnit")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("m²");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("ManagerID");

                    b.Property<decimal?>("SafetyThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(90m);

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Hoạt động");

                    b.Property<string>("WarehouseName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WarehouseType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WarehouseId")
                        .HasName("PK__Warehous__2608AFD9A6EB8906");

                    b.HasIndex("ManagerId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("ManufacturingERP.Models.WorkOrder", b =>
                {
                    b.Property<int>("Woid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WOID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Woid"));

                    b.Property<int?>("ActualQty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsUrgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Planned");

                    b.Property<int?>("TargetQty")
                        .HasColumnType("int");

                    b.Property<string>("Wocode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("WOCode");

                    b.HasKey("Woid")
                        .HasName("PK__WorkOrde__8D75747C73F86574");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "Wocode" }, "UQ__WorkOrde__94AAFED9725446CE")
                        .IsUnique();

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("ManufacturingERP.Models.WorkOrderItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("ActualQty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Planned");

                    b.Property<int>("TargetQty")
                        .HasColumnType("int");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderItems", (string)null);
                });

            modelBuilder.Entity("ManufacturingERP.Models.WorkOrderProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProgressID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<int?>("DefectQty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("MachineId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MachineID");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProducedQty")
                        .HasColumnType("int");

                    b.Property<string>("RecordedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StepNumber")
                        .HasColumnType("int");

                    b.Property<int?>("Woid")
                        .HasColumnType("int")
                        .HasColumnName("WOID");

                    b.Property<int?>("WorkOrderItemId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("WorkerID");

                    b.HasKey("ProgressId")
                        .HasName("PK__WorkOrde__BAE29C85157E5AB8");

                    b.HasIndex("Woid");

                    b.HasIndex("WorkOrderItemId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkOrderProgress", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK__UserRole__AF27604F0C898A9D");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("ManufacturingERP.Models.Attendance", b =>
                {
                    b.HasOne("ManufacturingERP.Models.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Attendances_Employees");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ManufacturingERP.Models.AuditLog", b =>
                {
                    b.HasOne("ManufacturingERP.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__AuditLogs__UserI__68487DD7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Bom", b =>
                {
                    b.HasOne("ManufacturingERP.Models.Material", "Child")
                        .WithMany("BomChildren")
                        .HasForeignKey("ChildId")
                        .HasConstraintName("FK__BOM__ChildID__71D1E811");

                    b.HasOne("ManufacturingERP.Models.Material", "Parent")
                        .WithMany("BomParents")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK__BOM__ParentID__70DDC3D8");

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ManufacturingERP.Models.EmployeeSchedule", b =>
                {
                    b.HasOne("ManufacturingERP.Models.Employee", null)
                        .WithMany("Schedules")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("ManufacturingERP.Models.Shift", "Shift")
                        .WithMany("EmployeeSchedules")
                        .HasForeignKey("ShiftId")
                        .HasConstraintName("FK__EmployeeS__Shift__208CD6FA");

                    b.HasOne("ManufacturingERP.Models.User", "User")
                        .WithMany("EmployeeSchedules")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__EmployeeS__UserI__1F98B2C1");

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Inventory", b =>
                {
                    b.HasOne("ManufacturingERP.Models.Material", "Material")
                        .WithMany("Inventories")
                        .HasForeignKey("MaterialId")
                        .IsRequired()
                        .HasConstraintName("FK_Inventory_Material");

                    b.HasOne("ManufacturingERP.Models.Warehouse", "Warehouse")
                        .WithMany("Inventories")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Wareh__29221CFB");

                    b.Navigation("Material");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Invoice", b =>
                {
                    b.HasOne("ManufacturingERP.Models.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Notification", b =>
                {
                    b.HasOne("ManufacturingERP.Models.User", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .HasConstraintName("FK__Notificat__Recip__236943A5");

                    b.HasOne("ManufacturingERP.Models.Role", "Role")
                        .WithMany("Notifications")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Notificat__RoleI__245D67DE");

                    b.Navigation("Recipient");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ManufacturingERP.Models.PasswordResetRequest", b =>
                {
                    b.HasOne("ManufacturingERP.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("ProcessedByAdminId");

                    b.HasOne("ManufacturingERP.Models.User", "User")
                        .WithMany("PasswordResetRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ManufacturingERP.Models.QualityControl", b =>
                {
                    b.HasOne("ManufacturingERP.Models.User", "Inspector")
                        .WithMany("QualityControls")
                        .HasForeignKey("InspectorId")
                        .HasConstraintName("FK__QualityCo__Inspe__0F624AF8");

                    b.HasOne("ManufacturingERP.Models.WorkOrder", "Wo")
                        .WithMany("QualityControls")
                        .HasForeignKey("Woid")
                        .HasConstraintName("FK__QualityCon__WOID__0C85DE4D");

                    b.HasOne("ManufacturingERP.Models.WorkOrderItem", "WorkOrderItem")
                        .WithMany("QualityControls")
                        .HasForeignKey("WorkOrderItemId")
                        .HasConstraintName("FK_QualityControl_WorkOrderItems");

                    b.Navigation("Inspector");

                    b.Navigation("Wo");

                    b.Navigation("WorkOrderItem");
                });

            modelBuilder.Entity("ManufacturingERP.Models.RolePermission", b =>
                {
                    b.HasOne("ManufacturingERP.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Routing", b =>
                {
                    b.HasOne("ManufacturingERP.Models.Material", "Product")
                        .WithMany("Routings")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Routings__Produc__74AE54BC");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ManufacturingERP.Models.StockTransaction", b =>
                {
                    b.HasOne("ManufacturingERP.Models.Material", "Material")
                        .WithMany("StockTransactions")
                        .HasForeignKey("MaterialId")
                        .HasConstraintName("FK__StockTran__Mater__7C494794");

                    b.HasOne("ManufacturingERP.Models.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .HasConstraintName("FK_StockTransactions_Partners");

                    b.HasOne("ManufacturingERP.Models.User", "TransByNavigation")
                        .WithMany("StockTransactions")
                        .HasForeignKey("TransBy")
                        .HasConstraintName("FK__StockTran__Trans__7D439ABD");

                    b.HasOne("ManufacturingERP.Models.Warehouse", "Warehouse")
                        .WithMany("StockTransactions")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("FK_StockTransactions_Warehouses");

                    b.Navigation("Material");

                    b.Navigation("Partner");

                    b.Navigation("TransByNavigation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ManufacturingERP.Models.User", b =>
                {
                    b.HasOne("ManufacturingERP.Models.Employee", "Employee")
                        .WithOne("UserAccount")
                        .HasForeignKey("ManufacturingERP.Models.User", "EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Warehouse", b =>
                {
                    b.HasOne("ManufacturingERP.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("FK_Warehouse_User");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ManufacturingERP.Models.WorkOrder", b =>
                {
                    b.HasOne("ManufacturingERP.Models.User", "CreatedByNavigation")
                        .WithMany("WorkOrders")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__WorkOrder__Creat__04E4BC85");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("ManufacturingERP.Models.WorkOrderItem", b =>
                {
                    b.HasOne("ManufacturingERP.Models.Material", "Product")
                        .WithMany("WorkOrderItemNavigations")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_WorkOrderItems_Materials");

                    b.HasOne("ManufacturingERP.Models.WorkOrder", "WorkOrder")
                        .WithMany("WorkOrderItems")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WorkOrderItems_WorkOrders");

                    b.Navigation("Product");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("ManufacturingERP.Models.WorkOrderProgress", b =>
                {
                    b.HasOne("ManufacturingERP.Models.WorkOrder", "Wo")
                        .WithMany("WorkOrderProgresses")
                        .HasForeignKey("Woid")
                        .HasConstraintName("FK__WorkOrderP__WOID__08B54D69");

                    b.HasOne("ManufacturingERP.Models.WorkOrderItem", "WorkOrderItem")
                        .WithMany("WorkOrderProgresses")
                        .HasForeignKey("WorkOrderItemId")
                        .HasConstraintName("FK_WorkOrderProgress_WorkOrderItems");

                    b.HasOne("ManufacturingERP.Models.User", "Worker")
                        .WithMany("WorkOrderProgresses")
                        .HasForeignKey("WorkerId")
                        .HasConstraintName("FK__WorkOrder__Worke__09A971A2");

                    b.Navigation("Wo");

                    b.Navigation("WorkOrderItem");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("ManufacturingERP.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__RoleI__656C112C");

                    b.HasOne("ManufacturingERP.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__UserI__6477ECF3");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Employee", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Schedules");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Material", b =>
                {
                    b.Navigation("BomChildren");

                    b.Navigation("BomParents");

                    b.Navigation("Inventories");

                    b.Navigation("Routings");

                    b.Navigation("StockTransactions");

                    b.Navigation("WorkOrderItemNavigations");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Role", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Shift", b =>
                {
                    b.Navigation("EmployeeSchedules");
                });

            modelBuilder.Entity("ManufacturingERP.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("EmployeeSchedules");

                    b.Navigation("Notifications");

                    b.Navigation("PasswordResetRequests");

                    b.Navigation("QualityControls");

                    b.Navigation("StockTransactions");

                    b.Navigation("WorkOrderProgresses");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("ManufacturingERP.Models.Warehouse", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("ManufacturingERP.Models.WorkOrder", b =>
                {
                    b.Navigation("QualityControls");

                    b.Navigation("WorkOrderItems");

                    b.Navigation("WorkOrderProgresses");
                });

            modelBuilder.Entity("ManufacturingERP.Models.WorkOrderItem", b =>
                {
                    b.Navigation("QualityControls");

                    b.Navigation("WorkOrderProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
